name: Upload

on:
  workflow_dispatch: 
  push:
    branches:
      - mwe

jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Install expect
        run: sudo apt-get install -y expect

      - name: SSH, send 1, run command
        run: |
          expect << 'END'
          set timeout 10
          spawn ssh -Y ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
          expect {
            "Passcode or option (1-1):" { send "1\r" }
            timeout { exit 1 }
          }
          expect "$ "
          send "cd youtube-livestream-processor\r"
          send "apptainer exec bash upload.sh | tee upload.out\r"
          expect "$ "
          END